### ISSUE TITLE
Deps missing?

### ISSUE THREAD

**Issue by grigio** [roman01la/react-horizon-example#1]
I had to install them manually

```
npm start                                         ⏎
...
Error: Cannot find module 'bufferutil' from '/Users/grigio/+persistant/Code/testing/react-horizon-example/node_modules/ws/lib'
Error: Cannot find module 'utf-8-validate' from '/Users/grigio/+persistant/Code/testing/react-horizon-example/node_modules/ws/lib'
```

**Comment by roman01la** [comment]
@grigio Ah yes, thanks. Those are dependencies of `ws` package which used by Horizon's client library. It has conditional `require` calls which breaks Browserify build. I've added those two as dependencies to this project.

Also notice that on very first run you need to call `generateSeats()` in browser's console to fill db table with data. I've added this to readme.
